application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  url: https://api.sendgrid.com/v3
  sender: "test@email.com"
  auth_code: "none"
